### ISSUE TITLE
Exporter scrape config error (or unclear docs?)

### ISSUE THREAD

**Issue by keithwegner** [Comcast/fishymetrics#74]
@derrick-dacosta thanks for offering to take a look.

I have a pretty simple Docker-Compose sandbox environment used to test various Prometheus exporters. While I have a number of exporters configured, I'm not _quite_ sure what I am doing wrong with Fishymetrics' exporter. My hunch is that there's a lack of clarity in the README for the scrape_config, and/or that I've configured it incorrectly.

Here are the relevant files:

---
**docker-compose.yaml**
```yaml
services:
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    ...


  redfish:
    image: dmtf/redfish-mockup-server:latest
    ports:
      - "8000:8000"


  fishymetrics_exporter:
    image: comcast/fishymetrics
    ports:
      - "9533:9533"
    environment:
      EXPORTER_PORT=9533
      BMC_USERNAME=admin
      BMC_PASSWORD=password
      BMC_TIMEOUT=15s
      BMC_SCHEME=http
      LOG_LEVEL=debug   
```
---
**prometheus.yml**
```yaml
...
scrape_configs:
  - job_name: 'fishymetrics'
    static_configs:
      - targets: ['redfish:8000']
    metrics_path: /scrape
```
---
I can run the following example commands successfully:
- cURL the Redfish container's `/redfish` API from my development machine:
  `curl localhost:8000/redfish/v1/Chassis`
- cURL the Redfish container's `/redfish` API from a container on the same Docker network:
  `docker run --rm --network sandbox_default curlimages/curl http://redfish:8000/redfish/v1/Chassis`
- cURL the Fishymetrics container's `/scrape` API from a container on the same Docker network:
  `docker run --rm --network sandbox_default curlmages/curl fishymetrics_exporter:9533/scrape?target=http://redfish:8000`

However, the Fishymetrics container itself is not successfully scraping the Redfish Mockup Server container. Its logs show the following info and error messages (I'm not copy/pasting the but this should suffice):
```
"level":"info"..., "caller":"fishymetrics/main.go:134", "msg":"started scrape", "app":"fishymetrics", "host":"<fishymetrics_container_id>", "module":"", "module" : "", "model":"", "target":"http://redfish:8000/redfish/v1/Chassis", "credential_profile":"",...`
"level:"error",..., "caller":"exporter/exporter.go:180", "msg":"error when getting chassis url from ", "app":"fishymetrics", "host":"<fishymetrics_container_id>", "error":"HTTP status 404"...
"level:"error",..., "caller":"fishymetrics/main.go:170", "msg":"failed to create chassis exporter", "app":"fishymetrics", "host":"<fishymetrics_container_id>", "error":"HTTP status 404"...
"level:"info",...,  "caller":"fishymetrics/main.go:80",  "msg":"finished handling", "app":"fishymetrics", "host":"<fishymetrics_container_id>", "module":"", "target":"http://redfish:8000/redfish/v1/Chassis", "sourceAddr":"172.x.x.5:12345", "method":"GET", "url":"/scrape?target=http://redfish:8000/redfish/v1/Chassis", "proto":"HTTP/1.1", "status":500"...
"level:"error",..., "caller":"fishymetrics/main.go:134", "msg":"started scrape", "app":"fishymetrics", "host":"<fishymetrics_container_id>", "module":"", "model":"", "target":"http://redfish:8000/redfish/v1/Chassis/1U", "credential_profile":"",...
"level:"error",..., "caller":"fishymetrics/main.go:134", "msg":"started scrape","app":"fishymetrics", "host":"<fishymetrics_container_id>", "module":"", "model":"", "target":"http://redfish:8000/redfish/v1/Chassis/1U", "credential_profile":"",...
```
I noticed a whitespace character in the first error message: "error when getting chassis url from ", implying no URL is set? Hopefully that is a helpful clue.
